apiVersion: v1
kind: Service
metadata:
  name: svc-auditoria-sesiones
  namespace: sispardt
  labels:
    app: svc-auditoria-sesiones
spec:
  type: NodePort
  selector:
    app: svc-auditoria-sesiones
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
