apiVersion: v1
kind: Service
metadata:
  name: svc-movimientos
  namespace: sispardt
  labels:
    app: svc-movimientos
spec:
  type: NodePort
  selector:
    app: svc-movimientos
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
