apiVersion: v1
kind: Service
metadata:
  name: svc-establecimientos
  namespace: sispardt
  labels:
    app: svc-establecimientos
spec:
  type: NodePort
  selector:
    app: svc-establecimientos
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
